### ISSUE TITLE
Business requirements  - Add API to monitor forms sent to employee 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#105]
**User story** 
As Hr manager , I want to see the progress of employee's forms 

**Tasks**
- [x] Add endpoints to API with proper json 

- [x] Receive the results from API and listed on a page 

- [x] Reminder option/ function  has to be implemented

**DOR**
List of progress is seen by HR manager on a table and reminder is ready to use 

**DOD**
HR manager can seethe progress of employee and can send the reminder to him/her. 

![image](https://user-images.githubusercontent.com/67949340/96470960-1c26cd80-122f-11eb-8391-1ba234af71b7.png)

**Comment by maggienow** [comment]
Kto obecnie się tym zajmuje?

**Comment by annapakula** [comment]
@adam-sas-on to chyba można zamknąć?
