### ISSUE TITLE
Business requirements - Add API to possible  forms to be sent to employee 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#106]
**User story** 
As Hr manager , I want to send one or more  forms to employee 

**Tasks**
- [x] Add endpoints to API with proper json 

- [x] Receive the results from API and listed on a page 

- [x] Reminder option/ function  has to be implemented

- [x] Add functionalities to forms

- [x] html template  "to send to employee" - combo of forms  

**DOR**
List of forms is seen by HR manager on a page and are  ready to send.

**DOD**
HR manager can send the reminder to him/her. 

![image](https://user-images.githubusercontent.com/67949340/96474053-a7559280-1232-11eb-9e33-580edd4016d9.png)

**Comment by maggienow** [comment]
Prośba do wszystkich o update, jak to wyglada na ten moment i kto sie tym zajmuje

**Comment by adam-sas-on** [comment]
I already did prototype serializer to get list of forms for a page from localhost:8000/manage/#/form_edit
When back-end database will have any set of forms then listing this page will be easier to develop.

**Comment by annapakula** [comment]
@adam-sas-on to chyba można zamknąć?

**Comment by adam-sas-on** [comment]
Task called `"Reminder option/ function has to be implemented"`
has to be explained and checked if it is finished or not.

**Comment by adam-sas-on** [comment]
It seems that task `Reminder option/ function has to be implemented`
is developed in issue #221
