### ISSUE TITLE
Business requirements QA section  for employee - view & functionality 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#131]
**User story** 
Employee(user) must have an access to Q&A page 

**Tasks**

- [ ] To create  view for Q&A section for employee

- [x] Create change in  left menu for employee - Q&A section must be seen

- [x] Add API for this 

- [ ] Add functionality for employee Q&A 

**DOR**
HR manager can create Q&A for employee which is seen in employee's menu  and Q&A section 

**DOD**
Employee sees Q&A in his/her menu and can read the content.

**Comment by maggienow** [comment]
@Michal-Roszyk - czy Ty masz może gdzies makiete tego Q&A? bo wydaje mi ,ze mielismy tam zrobic jeszcze przycisk zapisz.Na razie mamy tylko dodaj Q&A. Zobacz prosze jak to wyglada z punktu UX, bo wydaje mi sie,ze tak jak mamy teraz zrobione to malo czytalne jest dodawanie tego dla HRowca

**Comment by adam-sas-on** [comment]
Should an employee be able to edit questions and/or answers?
For now I'll do only listing

**Comment by Michal-Roszyk** [comment]
I sent to Magda the current Q&A view (Jennifer L.) and explain the user's (HR) journey at this stage
