### ISSUE TITLE
Business requirements - Saving   or editing  answers by employee 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#164]
**User story**
As an employee, I want to save or edit my answers before I send them to HR .

**TASKS**

- [x] Add this option to employee answers page
- [x] HR can see employee answers 
- [x] Employee  can save answers and send later 
- [x] Employee can send all answers immediately 

**DOD**
Employee can change his/her answers before sending

**Comment by maggienow** [comment]
@adam-sas-on Adam ,zobacz prosze czy taki zapis issue jest ok. Czy dodać może to do istniejącego issue już ?

**Comment by adam-sas-on** [comment]
Seems to be ok.
@maggienow 
How would you name the button to send answers and save
and button to send and confirm?
![Button to send answers](https://user-images.githubusercontent.com/52573736/104190033-c6238980-541b-11eb-9255-b9c93c2677ef.png)

**Comment by maggienow** [comment]
@adam-sas-on  "Zapisz odpowiedzi " i " Wyślij odpowiedzi"
