### ISSUE TITLE
UX changes implementation 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#165]
**UX suggestions** 
Below there are described some UX suggestions which should be implemented to MVP version.

**Tasks**
https://miro.com/app/board/o9J_leIxXIQ=/

HR profile 
- [x] Change name from "Forms" to "Catalogue" (drawing 4 Miro Jennifere Lawrence page) 
- [x] Add icons to HR manager left menu (drawing 1 Miro Jennifere Lawrence page) 
- [x] On the age "List of employees" there should be buttons : Add profile, Edit profile, Delete profile ( drawing 3 Miro Jennifere Lawrence page) 
- [x] Should be possibility to rename or add description to specific catalogue   (drawing 6 Miro Jennifere Lawrence page) 
- [x] Show created catalogues at left menu -  after click into "Wdrożenia" if there are any. ( drawing 6 Miro  Jennifer Lawrence page)
- [x] Drop and down list of forms after clicking into catalogue ( drawing 4 Miro  Jennifer Lawrence page)
- [x] Insert  button "Wdrożenia"  - my profile at employee page (drawing at  Joe Biden page) 
- [x] Insert button "Dodaj" i "Edytuj" at HR view , section Add employee 
- [x] Insert button "Wyślij" to List of catalogues / HR manager page 
- [x] Add labels to section "Info about company"
- [x] Add labels of progress - showing progress 
- [x] Update/ add new solutions done by UX in Miro : pop up window for adding catalogue, change colours of tags, view of employee answers

**Comment by maggienow** [comment]
@annapakula @adam-sas-on  - zobaczcie prosze,czy tyle Wam wystarczy,czy wszystko, co tam trzeba zmienić jest wypisane

**Comment by maggienow** [comment]
@Michal-Roszyk - dodałam Ciebie tutaj, żebyś w razie co mógl korygować albo dodawac komentarze

**Comment by annapakula** [comment]
@maggienow jeszcze:
- pokaż stworzone katalogi w lewym menu po kliknięciu we wdrożenia - jeśli jakieś są (6)
- rozwijana lista formularzy po kliknięciu w katalog  (4)

**Comment by maggienow** [comment]
@annapakula Ani dopisałam zgodnie z sugestią

**Comment by adam-sas-on** [comment]
`Add labels of progress - showing progress` seems to have something in common with issue  #119
