### ISSUE TITLE
Fixing - Renew password page 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#171]
**Issue**
After asking to access new password , Looper page  doesn't redirect you  to the proper , safe, page. 

**Tasks**

- [x] Change the link to redirect 

- [x] Redirect to https page 
- [x] Reminder / text about wrong passowrd should be seen by user

**Comment by maggienow** [comment]
@adam-sas-on Adam, zobacz prosze czy to o to chodziło

**Comment by adam-sas-on** [comment]
I think yes, that's it;
but maybe not renew but reset ;)
