### ISSUE TITLE
Business requirements - Add an e-mail notification for HR Manager

### ISSUE THREAD

**Issue by topi-chan** [binawork/OnlineOnboarding#178]
**User story** 
As HR manager I would like to be informed when employee completes the assignment. 

**Tasks**

- [ ] Informational e-mail is send to a HR Manager after an employee completes implementation assignment (it is an extra option, he/she doesn't have to wish additional e-mails, but it can help with tracking employees progress without the need to log into platform few times a day).
- [x] Backend works - server must remeber which HR sent to which employee, instead of informating all 
- [x] Change template text according to change redesign 
- [x] Frontend & UX - add new redesign according to Ania & Michal solutions
- [x] Backend - change info about which HR should get form, to remeber which HR manager sends which form to whom

**DOD**
Automatic email will be sent after completing the assignemnt by employee.

**Comment by topi-chan** [comment]
I need to learn REST framework to implement this issue (which I didn't know about before oO ;)) - so it will take some more time.

**Comment by maggienow** [comment]
Add new content of email reminder @maggienow

**Comment by adam-sas-on** [comment]
This feature might require secure HR mailbox against spamming,
but main task of this feature is implemented
so I decided to close it.
