### ISSUE TITLE
Business requirements - Removing sent catalogues /forms  

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#184]
**User story**
HR manager wants to have a possibility to remove wrongly sent forms eg.not proper procedure or form

**Tasks**

- [ ] Possibility to remove catalogues
- [ ] Possibility to remove dedicated forms 
- [ ] Remove sent catalogues from user profile 

**DOD**
HR manager can remove catalgues/forms and they are not seen by user/employee

**Comment by adam-sas-on** [comment]
I see that form can be removed already, so i checked `Possibility to remove dedicated forms`.
Removing catalogues from the list and from those sent to user still has to be made.
I found that this issue requires to use
`class PackageUsersSerializer(serializers.ModelSerializer):` in view class (back-end part of development).

**Comment by maggienow** [comment]
@Michal-Roszyk  Michal - prośba do Ciebie, żebyś z Adamem się skontaktował co do przycisku w view "Usuwanie formularzy"
