### ISSUE TITLE
Business requirements - Local storage info saved 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#192]
**User story** 
When I fill up forms and stop my work at some time, I want to come back to implemented information. 

**Tasks**
- [ ] Saving data and verification it from local storage @annapakula 
- [ ] Cleaning data when user will log off @annapakula 
- [ ] Safety of data from local storage (verification) @topi-chan 

**DOD**
Data are stored and can be used after acidentally stop working.

**Comment by maggienow** [comment]
@annapakula Ania ,sprawdz prosze czy takie maja byc taski i czy dobrze zrozumialam, co tam sie bedzie dzialo odnosnie local storage

**Comment by annapakula** [comment]
@maggienow bardziej:
Saving data in local storage about company  while editing
Verify data from local storage
Cleaning data in local storage when user will click Save button

Co do ostatniego, to @topi-chan raczej nie będzie potrzebny, a przynajmniej ja nie wiem, co miałby tu zrobić.

**Comment by maggienow** [comment]
Ania -dzieki. @adam-sas-on  sugerował, że backend ma tu sprawdzic zabezpieczenia tych danych. Adam- zweryfikuj to proszę.

**Comment by adam-sas-on** [comment]
Public repo so I will stick with english :wink: 
Yes, backend server will have to be careful and check if e.g.  `company_id` and `user_id` corresponds
like if user didn't manipulated them manually in browsers SQLite storage of data.
`is_valid()` of serializers would not be enough, I'm afraid.
Whatever it is gonna be it should be tested obviously :slightly_smiling_face:

**Comment by maggienow** [comment]
Thanks Adam
