### ISSUE TITLE
Business requirements - Add legend for HR forms/questions 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#201]
**User story** 
Theres is a need to add legend when HR creates forms . Legend is needed to show good/wrong answers.

**Tasks**

- [x] Legend will be seen when HR will create answers in forms
- [x] There must be different colours of answers- green for good, red for wrong
- [x] Legend will be shown as an example while creating forms
- [x] Legend with answers will be seen when employee completes forms
- [x]  Legend will be seen after pushing the right button.

**DOD**
Legend is in place while creating forms and is seen while answers from employee are sent.

**Comment by maggienow** [comment]
@annapakula Ania dodałam tam taski do tej legendy. Zobacz prosze czy to wszystkie, czy jeszcze cos tam trzeba zmienic. Bo z tego,co pamietam z rozmowy z UX, to jedna z przykladowymi odpowiedziami przy wprowadzaniu.A druga, po wprowadzeniu odpowiedzi przez pracownika.

**Comment by annapakula** [comment]
@maggienow Można by dodać, że legenda się pojawi po wciśnięciu odpowiedniego przycisku.
