### ISSUE TITLE
Business requirements - Email template

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#234]
User story 
As HR I want to have ready email template for different tasks in application 

**Tasks**

- [ ] Having ready to send email template for  - [ ] Register of employee - [ ]Acceptance answers by HR [ ] Reminder from HR to do forms  @annapakula 

- [ ] Desgin email template for different actions in application @Michal-Roszyk 
- [ ] Rendering for gingja @adam-sas-on 

**DOD**
When all views of email template are implelemented and user gets automatic responses in proper email template

**Comment by maggienow** [comment]
Pay attention to #183 and #178
