### ISSUE TITLE
Fixing  - Redesign section "Wdrożenia"

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#242]
There is a need to change sections after tests from users. 
**Tasks**

- [ ] Create new design of dashboard, menu section "Wdrozenia" - instead of "Wdrozenia" there must be "Dodaj wdrozenie"
- [ ] Add information section on left menu 
- [ ] Create new structure of "Dodaj wdrozenie"

**DOD**
New design is created and ready to be used by developers to implement

**Comment by maggienow** [comment]
@adam-sas-on @Michal-Roszyk Pay attention to button "Wstecz"  #241

**Comment by maggienow** [comment]
@Michal-Roszyk - Michał czy tutaj mamy wszystko zrobione?
