### ISSUE TITLE
Business requirements - Implement English version 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#255]
**User story**
As HR /employee I want to have option to choose ENG version of application 

**Tasks**

- [ ] Translate into English version all sections,  email templates  
- [ ] Adjust HR and user menu 
- [ ] Backend - detection of the user's language and selection of the appropriate content whci should be  sent
- [ ] Add flag "language" in order to change language of application  
- [ ] Frontend - choose the direction of maintenance and how to switch language ( model - do separate components of Eng version) or model - there are languages in application and application choose the right dictionary
