### ISSUE TITLE
Operations - Migration of data base between servers (new hosting) 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#256]
***User story **
Till the end of June we want to migrate our application from one data base to another. 

**Tasks**

- [ ] Set domain on new server 
- [ ] Set up Python environment  and start using Python 
- [ ] Transfer DJango app 
- [ ] Transfer components
- [ ] Collect static data from scrypts 
- [ ] Migration of data 
- [ ] Transfer existing accounts of users 

**DOD**
Tasks completed and application, website, user account  work properly without any troubles.
