### ISSUE TITLE
Business requirement - Contact button on current landing page 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#258]
**User story**
As a user I want to contact with customer service of application.

**Tasks**

- [ ] Add new button "Kontakt" on landing page  (right up corner on the landing page) 
- [ ] Add next to "Zaloguj" button 
- [ ] Create on server "Kontakt" mail on Polish version 
- [ ] Create on server "Contact" mail on English version 

**DOD**
Mail is created on server, add component and anyone can send the mail to us.
