### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by roktiw** [binawork/OnlineOnboarding#28]
**User Story**
As a Startup we want to host our app so @roktiw @maggienow and other users can see current aplha release.

**DOD**
I can enter URL to browser and see landing page of our app.

**We can host on**
Azure
HerokuApp
MyDevil.net

**What are req for hosting?**
Postgres
Python

**TODO**
- [x] buy domain
- [x] choose server provider
- [x] setup DNS zone
- [x] install Python
- [x] install PostgreSQL
- [x] deploy form Master to Production

**Comment by roktiw** [comment]
@MichalKandybowicz @adam-sas-on please write here in comment hosting requirements for @maciejjankowski

**Comment by adam-sas-on** [comment]
It should serve (be compatible with) python and postgreSQL for sure

**Comment by roktiw** [comment]
Please help us @maciejjankowski you are our only hope! 🧥🥼

**Comment by roktiw** [comment]
Domain www.onlineonboarding.net is on my Aftermarket account

**Comment by onlineonboarding** [comment]
@maciejjankowski potrzebujemy twojej pomocy

**Comment by maciejjankowski** [comment]
Dziś po południu - Możemy na mydevil.net to zrobić, bo mam tam konto. W tym czasie można poczytać jak to uruchomić https://wiki.mydevil.net/Django

**Comment by onlineonboarding** [comment]
Ja wczoraj na Panel13 dodałem ten projekt. Obczaj Maciek jak to będzie z dostępem dla Michała i Adama na serwer, bo zakładam, że nie chcesz być DevOpem w tym projekcie :) /Wiktor

**Comment by roktiw** [comment]
@maciejjankowski potrzebujemy pomocy. @MichalKandybowicz i @adam-sas-on probowali wgrać backup bazy Postgres i MyDevil tego nie wspiera

**Comment by maciejjankowski** [comment]
trzeba zrobić `ssh  bina@s47.mydevil.net`  - wtedy na serwerze można odpalić `psql`

**Comment by maciejjankowski** [comment]
https://wiki.mydevil.net/Django

**Comment by adam-sas-on** [comment]
A the moment the problem is to import requirements on a server
such as "djangorestframework"

**Comment by roktiw** [comment]
@MichalKandybowicz i've set right DNS on aftermarket. now you can see that domain www.onlineonboarding.net is connected to MyDevil

- Strona znajduje się w katalogu /usr/home/evil1/domains/onlineonboarding.net/public_python/public
wydaje mi się, że musicie w tym folderze umieścić index.html aplikacji
bo w tej chwili w tym folderze jest właśnie strona myDevil, która jest teraz wyświetlana
onlineonboarding.net
Strona Python dodana prawidłowo
- Strona znajduje się w katalogu /usr/home/evil1/domains/onlineonboarding.net/public_python/public
- Możesz usunąć ten plik (index.html),
- Pliki możesz umieszczać na serwerze za pomocą protokołu FTP, lub SFTP.
- Przykład uruchomienia strony w Django znajduje się na stronie wiki.mydevil.net/Python/Django.

W razie wątpliwości bądź pytań prosimy o kontakt.

**Comment by roktiw** [comment]
@adam-sas-on i am assiging you to this ticket couse @MichalKandybowicz told me you are in charge of it

please follow instructions on the website. i think you have to copy whole project to /usr/home/evil1/domains/onlineonboarding.net/public_python/public having in mind that the index.html must be visible in this catalog

**Comment by roktiw** [comment]
KennedyToday at 12:58 PM
source setenv.sh
python manage.py makemigrations
python manage.py migrate
