### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by roktiw** [binawork/OnlineOnboarding#3]
**Definition of Done**
Landing page with random copy from template BUT with two working buttons in the upper right Corner: "Register" and "Log In"

**Tasks**
- [x] Landing Page: https://uselooper.com/landing-page.html this should be 1st page that user will se when he will get on our page (/index.html when it will go public on server) . When you'll install it please create issue for @roktiw named "Landing Page - copywriting". And rename "Purchase now" button to Register than clone it and name "Log In"
- [x] Sign Up: https://uselooper.com/auth-signup.html
- [x] Sign In: https://uselooper.com/auth-signin-v1.html
- [ ] User Profile: https://uselooper.com/user-profile-settings.html

**Comment by adam-sas-on** [comment]
Current version of Looper views.
They still have to be associated with server side of page/service. They are currently supported by 3 methods i onboarding/views.py (temporary)
and 3 urls: "`bootstrap/signin`", "`bootstrap/sign-up`", "`bootstrap/dashboard`" (bootstrap branch)

![onboarding_bootstrap_signUp](https://user-images.githubusercontent.com/52573736/86930158-fc174680-c136-11ea-9cd3-fcb645ef5cf2.png)

Not connected with DJango auth App:
![onboarding_bootstrap_signin](https://user-images.githubusercontent.com/52573736/86930262-1e10c900-c137-11ea-87ea-674862618d57.png)

Central block is still to discuss:
![onboarding_bootstrap_dashboard](https://user-images.githubusercontent.com/52573736/86930322-2d901200-c137-11ea-9ae9-b0b07955ab38.png)

**Comment by roktiw** [comment]
This issue was renamed and splitted. Plese continue with views in following tasks:
#7 
#11 
#10
