### ISSUE TITLE
Business requirements - Navi bar

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#57]
**User story** 
As a user / admin,  I want to have navi bar in order to have possibility to search things. 

**Tasks**

- [x] Place navi bar in dashboard 

- [x] Navi bar will be seen in all views of application
- [x] Restyle navi bar  - blue color as suggested by @annapakula 
- [x] Navibar must be seen at empoyee and HR manager 
- [x] Navibar must be adjust to use in mobile version for HR manager profile  

**DOR**
Navi bar is placed in all views.

**DOD**
Navi bar is ready to use and it is working. 

[https://balsamiq.cloud/sviuzng/p1y6lm3/rFD1F](url)

**Comment by maggienow** [comment]
@annapakula - Ania tutaj ten issue otowrzylam ponownie.Bo myslę,ze stylizacja nav baru pod to podchodzi.Jak nie, to dawaj znać.

**Comment by maggienow** [comment]
@annapakula  - Ania to zedytuj proszę ten navbar , tak jak rozmawiałysmy na Discord. "tytuł formularza" nie ma być  wstawiony na sztywno,po to żeby się zmieniała nazwa formularza.

**Comment by annapakula** [comment]
W tym temacie pozostało przystosowanie navbaru do korzystania z mniejszych urządzeń u HR managera. Do tego lepiej byłoby wykonać najpierw refaktor kodu, gdyż w przypadku strony HR'a navbar jest umieszczany oddzielnie w wielu komponentach i wymagałoby to zmian w tychże komponentach.
Uważam, że lepiej najpierw przerzucić navbar do centralnego komponentu, a potem w tym jednym miejscu wykonać zmiany dotyczące responsywności. Może to zająć trochę czasu, więc myślę zrobić to w następnym tygodniu.

**Comment by maggienow** [comment]
Ania -zrobilam reopen issue i wstawilam, go na przyszlytydzien tak, jak pisalas.
