### ISSUE TITLE
Business requirements - HR MANAGER  - Dashboard/ Strona główna

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#60]
**User story** 
As a HR manager I want to have a dashboard where there will be a greeting  saying "Hello (name) (surname) !" . The dashboard will show me also which people are in the process of onboarding.

**Tasks**

- [x] Create Dashboard link in left menu 

- [ ] Create Dashboard with greeting(Hello...)  

- [x] Show the list of people in onboarding process below greeting 

**DOR**
The dasboard with all the features is created. There is a link to dasboard in left menu. 

**DOD**
I can see the dashboard with greeting and the list of people in onboarding process. 

[https://balsamiq.cloud/sviuzng/p1y6lm3/rFD1F](url)

**Comment by maggienow** [comment]
Add functionalities to this view

**Comment by maggienow** [comment]
@annapakula zajmie sie tym

**Comment by annapakula** [comment]
Added to dashboard:
- guide to add employee and content if there aren't any employees
- list of employees if there are some
