### ISSUE TITLE
User Regitration - Django and Looper

### ISSUE THREAD

**Issue by roktiw** [binawork/OnlineOnboarding#7]
**User Story**
As a user I want to be able to Register so I can have account and later log in.

**Definition of Done**
Register page styled with Looper.

**Tasks**
- [x] Style Registration Form form Django with Looper @adam-sas-on 
- [x] Verify that Django gets request from Registration Form styled with Looper @adam-sas-on 
- [ ]  Verify user account by sending email 

Balsamiq mockup
![image](https://user-images.githubusercontent.com/6304323/86902342-1e489e80-c10e-11ea-8599-ba88b3453d18.png)

Looper template
https://uselooper.com/auth-signin-v1.html
![image](https://user-images.githubusercontent.com/6304323/86902544-62d43a00-c10e-11ea-8601-0f281947e626.png)

**Comment by adam-sas-on** [comment]
Proposed Looper template versions are on  "Looper - Get to know first views we will be using" - I was not sure where to place them

**Comment by adam-sas-on** [comment]
current url `bootstrap/sign-up` on `bootstrap` branch

![Current sign-up](https://user-images.githubusercontent.com/52573736/86930158-fc174680-c136-11ea-9cd3-fcb645ef5cf2.png)
