### ISSUE TITLE
Business requirements- QA -backend -mockups, view, testing 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#82]
**User story**
As a HR manager , I want to have a Q&A page in order to put some information for employees. 

**Tasks**

- [ ] there is a need to create mockup of Q&A in Balsamiq

- [x] Add functionalities to Q&A page 

- [ ] UX must create view of this 

**DOR **

- [ ] View of Q&A is done

- [ ] Functionalities are implemetend

**DOD**
Q&A page tested and implemented

**Comment by maggienow** [comment]
@MichalKandybowicz - czy narysowałes to juz w Balsamiq?

**Comment by MichalKandybowicz** [comment]
zrobiłem backend do Q&A i endpoint, makiety nie wiem czy zrobie ja czy Michał od UX żeby było wszystko czytelniej

**Comment by maggienow** [comment]
Dobra, to zostawiamy na jutro to

**Comment by maggienow** [comment]
@adam-sas-on @annapakula - zapytajcie się prosze Michała (UX) , jak to ma być wizualnie - gdzie ma edytować HR , co ma widzieć pracownik. Gdzie to można wstawić? czy to będzie część dashboardu? czy nowy element

**Comment by maggienow** [comment]
@Michal-Roszyk to zadanie dla Ciebie. W razie pytań ,kontaktuj się prosze z Michałem albo Adamem

**Comment by maggienow** [comment]
@annapakula - tutaj proszę rób update, tego co robisz
@Michal-Roszyk - prośba do Ciebie, żebyś stworzył widok dla Q&A i funkcjonalności
