### ISSUE TITLE
UX aspects 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#86]
**User story**
As a user I want to have functional layout 

**Tasks**

- [x] contact with Michał,UX designer, in order to introduce him into project 

- [x] Michał, to do audit of functionalities of our app 

- [ ] Adjust layout to requirements

**Comment by maggienow** [comment]
UX aspectes are discussed.
