### ISSUE TITLE
Business requirements - employee welcome dashboard 

### ISSUE THREAD

**Issue by maggienow** [binawork/OnlineOnboarding#95]
User story 
As an employee , I want to see when I log into app, the dashobard with company info, some video, photos.

**Tasks**

- [x] Design such view in Baslamiq

- [x] Decide about component functionalities 

- [x] Add functionalities to component

**DOR**

- [x] View is designed

- [x] Dashboard with functionalities implemented

**DOD**
Dashobar is seen by employee with the above functionalties

**Comment by adam-sas-on** [comment]
The last one thing to make it done is to make that welcome dashboard
is visible only once - when the employee log in at the beginning.
